# Reconstruction configuration file

defaults:
  - encoder: vgg19
  - generator: relu7generator

decoded_features:
  name: ImageNetTest_deeprecon_VGG19
  path: ./data/decoded_features/within/caffe/VGG_ILSVRC_19_layers/
  subjects:
    - sub01

  rois:
    - VC
  decoders:
    path: ../data/pre-trained/decoders/ImageNetTraining/deeprecon_pyfastl2lir_alpha100_vgg19_allunits/caffe/VGG_ILSVRC_19_layers

icnn:
  num_iteration: 200
  feature_scaling: feature_std_train_mean_center

output:
  path: ./data/reconstruction/icnn/within/
  prefix: recon_image-
  ext: tiff

