# Reconstruction configuration file

defaults:
  - encoder: vgg19
  - generator: relu7generator

decoded_features:
  name: ImageNetTest_deeprecon_VGG19
  path: ./data/decoded_features/ImageNetTest/deeprecon_originals/VGG19
  subjects:
    - sub-01
    # - sub-02
    # - sub-03
  rois:
    - VC
  decoders:
    path: ../data/pre-trained/decoders/ImageNetTraining/deeprecon_pyfastl2lir_alpha100_vgg19_allunits/caffe/VGG_ILSVRC_19_layers

icnn:
  num_iteration: 200
  feature_scaling: feature_std_train_mean_center

output:
  path: ./data/reconstruction/icnn/${_analysis_name_}_${encoder.name}_${generator.name}_scaling_${icnn.feature_scaling}_${icnn.num_iteration}iter/decoded/${decoded_features.name}
  prefix: recon_image-
  ext: tiff
