# Reconstruction configuration file

defaults:
  - encoder: vgg19
  - generator: relu7generator

decoded_features:
  name: ImageNetTest_deeprecon_VGG19
  path: /
  subjects:
    - SA
  rois:
    - VC
  decoders:
    path: /

icnn:
  num_iteration: 200
  feature_scaling: feature_std_train_mean_center

output:
  path: ./data/reconstruction/icnn/${_analysis_name_}_${encoder.name}_${generator.name}_scaling_${icnn.feature_scaling}_${icnn.num_iteration}iter/decoded/${decoded_features.name}
  prefix: recon_image-
  ext: tiff

evaluation:
  true_image:
    path: /home/nu/data/contents_shared/ImageNetTest/source
    ext: JPEG
