# fMRI data ##################################################################

training fmri:
  sub-01:
    - ./data/fmri/sub-01_NaturalImageTraining.h5
  # sub-02:
  #   - ./data/fmri/sub-02_NaturalImageTraining.h5
  # sub-03:
  #   - ./data/fmri/sub-03_NaturalImageTraining.h5

test fmri:
  sub-01:
    - ./data/fmri/sub-01_NaturalImageTest.h5
  # sub-02:
  #   - ./data/fmri/sub-02_NaturalImageTest.h5
  # sub-03:
  #   - ./data/fmri/sub-03_NaturalImageTest.h5

rois:
  VC:  ROI_VC = 1

# The number of voxels used in feature decoding
rois voxel num:
  VC:  500

label key:
  image_index

# DNN features ###############################################################

training feature dir:
  - ./data/features/ImageNetTraining

test feature dir:
  - ./data/features/ImageNetTest

network:
  caffe/VGG19

layers:
  - conv1_1
  - conv1_2
  - conv2_1
  - conv2_2
  - conv3_1
  - conv3_2
  - conv3_3
  - conv3_4
  - conv4_1
  - conv4_2
  - conv4_3
  - conv4_4
  - conv5_1
  - conv5_2
  - conv5_3
  - conv5_4
  - fc6
  - fc7
  - fc8

# Feature decoding ###########################################################

feature decoder dir:
  ./data/pre-trained/decoders/ImageNetTraining/deeprecon_pyfastl2lir_alpha100_vgg19_allunits

# Decoded features
decoded feature dir:
  ./data/pre-trained/decoded_features/ImageNetTest/deeprecon_fmriprep_pyfastl2lir_alpha100_allunits

# Learning parameters
alpha: 100
chunk axis: 1

# Figure output
decoding figure dir:
  ./data/figures/feature_decoding/ImageNetTest/deeprecon_fmriprep_pyfastl2lir_alpha100_allunits
