# @package _group_

name: relu7generator
input_layer: relu7
parameters_file: ./data/models/bvlc_reference_caffenet_generator_ILSVRC2012_Training/generator_relu7.pt
image_mean_file: ./data/models/bvlc_reference_caffenet/ilsvrc_2012_mean.npy
feature_std_file: ./data/models/bvlc_reference_caffenet/estimated_cnn_feat_std_bvlc_reference_caffenet_ImgSize_227x227_chwise_dof1.mat
latent_shape: [4096]
latent_upper_bound_file: ./data/models/bvlc_reference_caffenet_generator_ILSVRC2012_Training/relu7_act_range_3x.txt
latent_upper_bound_shape: [4096]
